// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiVG_yCyWI7xEFB7rL2SBlVmWij8YLgds',
    appId: '1:669391209154:web:d34de5a49e71e769aff15b',
    messagingSenderId: '669391209154',
    projectId: 'flash-chat-54954',
    authDomain: 'flash-chat-54954.firebaseapp.com',
    storageBucket: 'flash-chat-54954.appspot.com',
    measurementId: 'G-N22TWB7147',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjuRQjW2lZeo7_bJbsk-DFgzML0hFB3E',
    appId: '1:669391209154:android:3910bf5591c1e910aff15b',
    messagingSenderId: '669391209154',
    projectId: 'flash-chat-54954',
    storageBucket: 'flash-chat-54954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM5mY8nR6cmk4u699szDEkMuy7xE_a2eY',
    appId: '1:669391209154:ios:c86d868868050e0daff15b',
    messagingSenderId: '669391209154',
    projectId: 'flash-chat-54954',
    storageBucket: 'flash-chat-54954.appspot.com',
    iosClientId: '669391209154-gonu3ksi7qnud82og28o3iuabtmec6e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
